# server 설정
server:
  port: 9091

---
# datasource 설정
spring:
  datasource:
    hikari:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:log4jdbc:mysql://localhost:3306/sample?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      username: sample
      password: password1!

---
# profiles 설정
spring:
  profiles:
    active: local
    group:
      local: logging-type-console, logging-level-local
      dev: logging-type-file, logging-level-dev